db:
  url: jdbc:postgresql://localhost:5432/my-enterprise-project
  username: postgres
  password: admin123qwe!
  pool.size: 6
spring:
#  profiles.active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/my-enterprise-project
    username: postgres
    password: admin123qwe!
  jpa.properties.hibernate:
    show_sql: true
    format_sql: true
    hbm2ddl.auto: update
logging:
  level:
    root: error
app:
  media:
    bucket: C:\JPr\my-enterprise-poject\images