
SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE pizzeria.order_entries RESTART IDENTITY;
TRUNCATE TABLE pizzeria.orders RESTART IDENTITY;
TRUNCATE TABLE pizzeria.pizzas RESTART IDENTITY;
TRUNCATE TABLE pizzeria.address RESTART IDENTITY;
TRUNCATE TABLE pizzeria.users RESTART IDENTITY;
TRUNCATE TABLE pizzeria.roles RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;